source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.1"

target "Aerocom" do
    pod "MagicalRecord",            "2.3.0"
    pod "CocoaLumberjack"
    pod "SDWebImage",               "~> 3.7.1"
    pod "libPhoneNumber-iOS",       "~> 0.8.8"
    pod "AFNetworking",             "~> 3.1.0"
    pod "Bugtags",                  "~> 1.2.6"
    pod "RealReachability",         "~> 1.1.1"
    pod "UMengAnalytics",           "~> 3.6.6"
    pod "FBRetainCycleDetector",    "~> 0.1.3"
end

